13060 MainProcess 2023-05-15 10:30:06,372
Traceback (most recent call last):
  File "C:\Users\Stefan Berlind\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 706, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Stefan Berlind\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 694, in main_entry
    args.func(ctx, args)
  File "C:\Users\Stefan Berlind\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 237, in cmd_gen
    builder.process(options)
  File "C:\Users\Stefan Berlind\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 147, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\Stefan Berlind\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\core\__init__.py", line 80, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 871, in pre_build
  File "<maker>", line 743, in build
RuntimeError: out of license
